import '@/app/ui/global.css'; //figure css stuff out??
import { roboto } from '@/app/ui/fonts';
// import { lusitana } from '@/app/ui/fonts';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
      {/* <body className={`${roboto.className} antialiased`}>{children}</body> */}
      {/* <body className={`${lusitana.className} antialiased`}>{children}</body> */}
    </html>
  )
}
